### ISSUE TITLE
duplicate values

### ISSUE THREAD

**Issue by sstarcher** [aquasecurity/saas-terraform-connection#2]
```
Error: aws_iam_role.cloudsploit_cross_account_role: resource repeated multiple times



Error: aws_iam_role_policy_attachment.cloudsploit_cross_account_attach: resource repeated multiple times
```

**Comment by majormoses** [comment]
I ran into the same issue myself pretty sure I know what the issue is, I will fork and PR a fix.

**Comment by sstarcher** [comment]
The fix is pretty trivial it just needs to not use the same exact name.  The resource `cloudsploit_cross_account_role` is repeated twice.

**Comment by majormoses** [comment]
ya I am getting sidetracked but I think I might do some minor enhancements while I am at it so that the module you can tell it whether you are using govt or not.

**Comment by majormoses** [comment]
see #3 for fixes/enhancements

**Comment by matthewdfuller** [comment]
@sstarcher @majormoses - really appreciate you looking into this - I'll merge your PR shortly.
